/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.facturapro.GUI;

import com.mycompany.facturapro.Bill.Bill;
import com.mycompany.facturapro.Users.Person;
import com.mycompany.facturapro.Users.NaturalPerson;
import com.mycompany.facturapro.product.Product;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    private Person vendedor = new NaturalPerson("admin", 123333);
    private List<Product> inventario;
    private List<Person> clients;
    private List<Bill> facturas;
    String product;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.inventario = new ArrayList<>();
        this.clients = new ArrayList<>();
        this.facturas = new ArrayList<>();
        JOptionPane.showMessageDialog(null, "Bienvenido " + vendedor.getNombre());
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        btnBuscarFactura = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("FacturaPro");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        btnNuevoCliente.setText("Nuevo cliente");
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);

        btnGenerarFactura.setText("Generar factura");
        btnGenerarFactura.addActionListener(this::btnGenerarFacturaActionPerformed);

        btnBuscarFactura.setText("Buscar factura");
        btnBuscarFactura.addActionListener(this::btnBuscarFacturaActionPerformed);

        btnHistorial.setText("Histórico de facturas");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        btnEliminarCliente.setText("Eliminar cliente");
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);

        btnProduct.setText("Menú productos");
        btnProduct.addActionListener(this::btnProductActionPerformed);

        jButton1.setText("Facturas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(btnGenerarFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBuscarFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        String element = JOptionPane.showInputDialog("Ingrese el nombre del cliente a buscar" + clients.stream().map(Person::getNombre).toList());
        
        Person cliente = clients.stream()
                .filter(client -> client.getNombre().equalsIgnoreCase(element))
                .findFirst()
                .orElse(null);
        
        if(!element.equals("") && !element.equals(" ") && element != null){
            if(cliente != null){
                JOptionPane.showMessageDialog(null, "Nombre: " + cliente.getNombre() + "\n" + cliente.getTypeId() + ": " + cliente.getId());
            }else{
                JOptionPane.showMessageDialog(null, "El cliente ingresado no existe");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No ha ingresado ningún valor");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        
        NewClientScreen pantalla = new NewClientScreen(this);
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        // TODO add your handling code here:
        long price = 0;
        String element = JOptionPane.showInputDialog("Ingrese el nombre del cliente a facturar (" + clients.stream().map(Person::getNombre).toList() + ")");
        int cantidad;
        List<Product> productosFacturar = new ArrayList<>();
        
        Person cliente = clients.stream()
                .filter(client -> client.getNombre().equalsIgnoreCase(element))
                .findFirst()
                .orElse(null);
        
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "El cliente " + element +" no existe");
        }else{
            while(true){
                product = JOptionPane.showInputDialog("Ingrese el producto que desea agregar (" + inventario.stream().map(p -> p.getName() + " - " + p.getStock() + ")\n").toList());
                Product producto = inventario.stream()
                    .filter(p -> p.getName().equalsIgnoreCase(product))
                    .findFirst()
                    .orElse(null);
                while(true){
                    if(producto != null){
                        break;
                    }else{
                        if(inventario.size() == 0){
                            JOptionPane.showMessageDialog(null, "No hay ningún producto en el inventario");
                            break;
                        }else{
                            JOptionPane.showMessageDialog(null, "El dato ingresado no es válido");
                            product = JOptionPane.showInputDialog("Ingrese el producto que desea agregar (" + inventario.stream().map(p -> p.getName() + " - " + p.getStock() + ")\n").toList());
                            producto = inventario.stream()
                            .filter(p -> p.getName().equalsIgnoreCase(product))
                            .findFirst()
                            .orElse(null);
                        }
                    }
                }
                if(inventario.size() != 0){
                    while(true){
                        try{
                            cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad que desea facturar"));
                            break;

                        }catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(null, "El valor ingresado no es válido");
                        }
                    }
                
                while(true){
                    if(cantidad > producto.getStock()){
                        JOptionPane.showMessageDialog(null, "El valor ingresado no es válido");
                        cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad que desea facturar"));
                    }else{
                        price = price+producto.getPrice()*cantidad;
                        producto.setCantidad(cantidad);
                        producto.setStock(producto.getStock()-producto.getCantidad());
                        productosFacturar.add(producto);
                        break;
                    }
                }
                
                String opcionElegida = JOptionPane.showInputDialog("Ingrese 1 si desea factura más productos, y 2 si no desea facturar más");
                while(true){
                    if(!opcionElegida.equals("1") && !opcionElegida.equals("2")){
                        JOptionPane.showMessageDialog(null, "El valor ingresado no es válido");
                        opcionElegida = JOptionPane.showInputDialog("Ingrese 1 si desea factura más producto, y 2 si no desea facturar más");
                    }else{
                        break;
                    }
                }
                
                if(opcionElegida.equals("2")){
                    break;
                }else{
                    break;
                }
                }else{
                    break;
                }
                
            }
            
            if(productosFacturar.size() != 0){
                Bill factura = new Bill(vendedor, cliente, productosFacturar, price);
                facturas.add(factura);

                JOptionPane.showMessageDialog(null, factura.printBill());
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo generar la factura");
            }
            
            
        }
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaActionPerformed
        // TODO add your handling code here:
        String element = JOptionPane.showInputDialog("Ingrese el nombre del cliente del cual desea realizar la búsqueda de la factura"+ clients.stream().map(Person::getNombre).toList() + ")");
        
        Person cliente = clients.stream()
                .filter(client -> client.getNombre().equalsIgnoreCase(element))
                .findFirst()
                .orElse(null);
        
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "El cliente ingresado no existe");
        }else{
            JOptionPane.showMessageDialog(null, facturas.stream()
                                                    .filter(p -> p.getClient().getNombre().equalsIgnoreCase(element))
                                                    .map(p -> p.printBill() + "\n")
                                                    .toList()); 
        }
    }//GEN-LAST:event_btnBuscarFacturaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, facturas.stream().map(p -> p.printBill() + "\n").toList());
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
        ProductScreen pantalla = new ProductScreen(inventario, this);
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:

        String element = JOptionPane.showInputDialog("Ingrese el nombre del cliente que desea eliminar "+ clients.stream().map(Person::getNombre).toList() + ")");

        Person cliente = clients.stream()
        .filter(client -> client.getNombre().equalsIgnoreCase(element))
        .findFirst()
        .orElse(null);

        if(cliente == null){
            JOptionPane.showMessageDialog(null, "El cliente ingresado no existe");
        }else{
            clients.remove(cliente);
            JOptionPane.showMessageDialog(null, "Cliente eliminado");
        }

    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    public void setClient(Person p){
        clients.add(p);
        JOptionPane.showMessageDialog(null, "Cliente agregado");
    }


    public List<Person> getClients() {
        return clients;
    }

    public void setInventario(List<Product> inventario) {
        this.inventario = inventario;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
